# Generated by Django 5.2 on 2025-08-19 17:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_company_internship'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='posted_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
