# Generated by Django 5.2 on 2025-08-20 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_skill_internship_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internship',
            name='skills',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.AddField(
            model_name='internship',
            name='skills',
            field=models.CharField(blank=True, help_text='Comma-separated list of required skills', max_length=250),
        ),
    ]
