# Generated by Django 5.2 on 2025-08-21 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_remove_internship_skills_delete_skill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipapplication',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Under Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
